language: go
sudo: false

matrix:
  include:
  - go: tip
    os: linux
    env: CROSS_COMPILE=true

before_install:
- if [ "$CROSS_COMPILE" = "true" ]; then sudo apt update; fi

install:
- if [ "$CROSS_COMPILE" = "true" ]; then sudo apt install gcc-mingw-w64 libc6-dev-i386; fi

script:
- go build; mkdir upload; zip upload/pg_tileserv_snapshot_linux.zip pg_tileserv README.md
- if [ "$TRAVIS_OS_NAME" = "linux" -a "$CROSS_COMPILE" = "true" ]; then env CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc go build -v; zip upload/pg_tileserv_snapshot_windows.zip pg_tileserv.exe README.md; fi

deploy:
  on:
    repo: pramsey/pg_tileserv
    branch: master
  provider: s3
  bucket: postgisftw
  local_dir: "./upload"
  overwrite: true
  verbose: true
  edge: true
  cleanup: false
  access_key_id:
    secure: "g7bcteJJsu4Uab/Y7aig+9u+9fFMUbeCxxSszJRSlGlFp34lOP9uRITsCBQ+bS32e2efAmf/6F52IzCBWJNrAMhYDWJAlOjWCYtUD+kFAUj7Ua5VOr5/RtbI5Bplpq1zLjVLwSuoEIFOFByj9PtKwFitc04vIz6XhfoJs9S1qeIrEznFCchrOL/YJIZqAoHhi4NF2KxfrMd1XA1mJZPpoC1IDqJW0iABaD97xSWtNvKW6zO/0IzPLmXuvDsYvUcjvFMTG3YJ8HpF+hiFwFJOI3F/CK7Ee3tF2Q4YcYx7GrQL2CpNTnQOM01KP0sZg/HxR9TH2/esPqZWbGPsGBwzYOF6sf3oNM/KHis7A59LRzv3DG7NuweDJu8JcS2a8ztpGfsHCwWHwvaaaFHgSU8arHwPYnTH1F+6e2uCyvFdagM/5yrrHxhdGot0WZDdReR1BgPw7h7v0IhS7Te8tpTJsUx92CJQNV1wQLEKuj3u/eDEzDk0NW4516KaZap7czn0pdhH7ZMRXKMw1RwWISH5iYKQPDwPTnkZSeGcQ1IbOltAk6WRBfVAv3z6Rh3lLXFhacOy0GUxmuwdDvPyEUyFvOrW3xolJocX15UZMI5TB/6ZDPqrj0/HYdFtRua7B9B3d0iAYBu07OwqSP0ZWhBVEzJE+KBAFEiw1b23oCoTbbs="
  secret_access_key:
    secure: "MtMyeiqy8QC+OmZANiv7VhfWF7i+FY7uVJxoyyArJe/O6CPsm41p985k/sBcSkHzN7ujDKxU6yhlF+wcz89n9M4rWBZ8XI1SZ07HAVdZO3kUp/QL6dI/q54If+NmaVeGR9DbcLY4I9YbKuhQ0D1UJ4g5BWqycaYSxl+nb9IiNjVVNpTC5RT1aKOLW5Ep2/dDU8E/jfC7Xxhok1iP4/vbHzgKP2WtOHIPo+m+V/jweCKCSjoxe0Efd+oa5xSARc03eqPECQBcTZjAe+PBqt8yRhJBA2Ih0RAc3y4+ng1dMGYK8FiIhQgDnalTd+aJT9KXDIQULwFDtojzWM2VWmbLjCpUtHF//ZUHi6oS5MA/rEOZDmCXFNEfdC5obJPimP1GwXtoXkG2J9Igup9nuhiXti7+RMi0XSrcb9aJrrqerGwB8cNdYswzzcrp1FwlZM2O25tShZ3XI1AR54WRDOGL5f9VoCJmRpohP37pGn2w0lTfp3qEjfBDIDutz4hZbQ2U9MTrPId2rBErc0ezpZvg56cIsV7cMu7r0L3eoX3yFOvR5SnG9EVlpHngHcX610lXnllsJcSSddAKp2uXb8dHae67eRUJOhM66DofU/hy6qnf3H6jTMxWKwfQTKDZ39f1VjKr0ZOcObv8BDXZpG0GtECLqeh702FCQy+cwSAKp8Q="

    
