language: go
sudo: false
matrix:
  include:
  - go: tip
    os: linux
    env: CROSS_COMPILE=true
before_install:
- if [ "$CROSS_COMPILE" = "true" ]; then sudo apt update; fi
install:
- if [ "$CROSS_COMPILE" = "true" ]; then sudo apt install gcc-mingw-w64 libc6-dev-i386;
  fi
script:
- go build; mkdir upload; zip upload/pg_tileserv_snapshot_linux.zip pg_tileserv README.md
- if [ "$TRAVIS_OS_NAME" = "linux" -a "$CROSS_COMPILE" = "true" ]; then env CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc go build -v; zip upload/pg_tileserv_snapshot_windows.zip pg_tileserv.exe README.md; fi
deploy:
  on:
    repo: CrunchyData/pg_tileserv
    branch: master
  provider: s3
  region: us-east-1
  bucket: postgisftw
  local_dir: "./upload"
  overwrite: true
  verbose: true
  edge: true
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  cleanup: false


