on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    if: github.repository == 'CrunchyData/pg_tileserv'
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build ARM64
      run: make TARGETARCH=arm64 multi-stage-docker

    - name: Build x86_64
      run: make TARGETARCH=amd64 multi-stage-docker

    - name: Docker Upload
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        DOCKER_REPO: pramsey/pg_tileserv
      run: |
        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        docker push --all-tags $DOCKER_REPO
